export const enum UserActions {
  SET_USER = 'SET_USER',
  SET_USER_TELEGRAM_ID = 'SET_USER_TELEGRAM_ID',
  SET_USER_TELEGRAM_USERNAME = 'SET_USER_TELEGRAM_USERNAME',
  SET_USER_NAME = 'SET_USER_NAME',
  SET_USER_LASTNAME = 'SET_USER_LASTNAME',
  SET_USER_TGAPP = 'SET_USER_TGAPP',
}
